spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pet_clinic_dev?serverTimezone=UTC&useSSL=true
    username: dev
    password: pet

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: imad_database_create.sql